### ISSUE TITLE
Todo this week

### ISSUE THREAD

**Issue by dioptre** [SFDevLabs/galacticWiki#2]
- [ ] Run through script
- [ ] Make it look like its usable - fuck off actual usability
- [x] Verify product as it is, metric - engagement, immediate usability, "i want this", "i'll use this" 
- [x] ~100~ 30 people user results
- [ ] Get closer to choosing from high level options

**Comment by dioptre** [comment]
People wont use this or need it.
